# Generated by Django 2.0.6 on 2018-06-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Learn_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='lab_num',
            field=models.IntegerField(default=0),
        ),
    ]
