# Generated by Django 2.0.5 on 2018-06-12 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180607_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={'verbose_name': '实验', 'verbose_name_plural': '实验'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='learn',
            options={'verbose_name': '学习记录', 'verbose_name_plural': '学习记录'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '消息', 'verbose_name_plural': '消息'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': '帖子节点', 'verbose_name_plural': '帖子节点'},
        ),
        migrations.AlterModelOptions(
            name='publish',
            options={'verbose_name': '发帖', 'verbose_name_plural': '发帖'},
        ),
        migrations.AlterModelOptions(
            name='replay',
            options={'verbose_name': '回帖', 'verbose_name_plural': '回帖'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': '实验报告', 'verbose_name_plural': '实验报告'},
        ),
        migrations.AlterModelOptions(
            name='upload',
            options={'verbose_name': '课程上传', 'verbose_name_plural': '课程上传'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='Learn_minutes',
        ),
        migrations.AddField(
            model_name='user',
            name='learn_minutes',
            field=models.IntegerField(default=0, verbose_name='累计实验时间'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='课程ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='课程描述'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(max_length=200, unique=True, verbose_name='课程图片'),
        ),
        migrations.AlterField(
            model_name='course',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Label', verbose_name='课程标签'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='课程名'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='content',
            field=models.CharField(max_length=200, unique=True, verbose_name='实验内容'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='did',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='实验ID'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(max_length=100, verbose_name='实验名'),
        ),
        migrations.AlterField(
            model_name='label',
            name='lid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='标签ID'),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='标签名'),
        ),
        migrations.AlterField(
            model_name='learn',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course', verbose_name='学习课程'),
        ),
        migrations.AlterField(
            model_name='learn',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='学习时间'),
        ),
        migrations.AlterField(
            model_name='learn',
            name='last_lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lab', verbose_name='最后学习实验'),
        ),
        migrations.AlterField(
            model_name='learn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='学习用户'),
        ),
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='消息时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=1024, verbose_name='消息内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(max_length=20, verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=30, verbose_name='节点名称'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='content',
            field=models.CharField(max_length=1024, verbose_name='发帖内容'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Node', verbose_name='所属节点'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='publish_datetime',
            field=models.DateTimeField(verbose_name='发帖时间'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='replay_datetime',
            field=models.DateTimeField(verbose_name='最新回帖时间'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='replay_num',
            field=models.IntegerField(default=0, verbose_name='回帖次数'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='title',
            field=models.CharField(max_length=100, verbose_name='帖子标题'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='发帖用户'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='view_num',
            field=models.IntegerField(default=0, verbose_name='查看次数'),
        ),
        migrations.AlterField(
            model_name='replay',
            name='content',
            field=models.CharField(max_length=1024, verbose_name='回帖内容'),
        ),
        migrations.AlterField(
            model_name='replay',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='回帖时间'),
        ),
        migrations.AlterField(
            model_name='replay',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Publish', verbose_name='所属帖子'),
        ),
        migrations.AlterField(
            model_name='replay',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='回帖用户'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.CharField(max_length=1024, verbose_name='报告内容'),
        ),
        migrations.AlterField(
            model_name='report',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='report',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='report',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lab', verbose_name='所属实验'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course', verbose_name='上传课程'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='上传用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_or_school',
            field=models.CharField(max_length=100, verbose_name='学校或工作'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lab_num',
            field=models.IntegerField(default=0, verbose_name='实验次数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=100, verbose_name='工作状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='用户名'),
        ),
    ]
